Ext.define('SDT.view.dashboardAdmin.cards.Save', {
    extend: 'Ext.ux.panel.Card',
    alias: 'widget.save',
    description: 'Your dashboard has beeen created and added as a menu item to the Dashboards pulldown. You have the option to archive this dashboard at anytime. See the Wiki for managing Dashboards.',
    title: 'Save',
    trackResetOnLoad: true,
    itemId: 'saveCard',
    layout: 'fit',
    showTitle: true,
    scrollable: true,
    items: [{
        xtype: 'dataview',
        style: 'background-color:#FFF;',
        padding: 5,
        itemSelector: 'div.thumb-wrap',
        emptyText: 'No data available',
        store: {
            fields: [
                'title',
                'description',
                'active',
                'dataIndex',
                'charts',
                'criteria',
                'filters'
            ]
        },
        tpl: Ext.create('Ext.XTemplate',
            '<tpl for=".">',
            '<h2>Summary</h2><br>',
            'Title: {title}<br>',
            'Description: {description}<br>',
            'Active: ',
            '<tpl if="!active">',
            'No',
            '</tpl>',
            '<tpl if="active">',
            'Yes',
            '</tpl>',
            '<br>',
            'Type:</b> {dataIndex}<br>',
            '<hr>',
            '<h2>Applied Filters</h2>',
            '<table width="100%" border="0">',
            '<tr><td width="10%"><b>Field Label</b><td width="10%"><b>Field Name</b></td><td width="10%"><b>Type</b></td><td width="10%"><b>Operator</b></td><td width="20%"><b>Value</b></td><td width="30%"><b>From</b></td><td width="30%"><b>To</b></td></tr>',
            '<tpl for="filters">',
            '<tr><td>{fieldLabel}</td><td>{fieldName}</td><td>{type}</td><td>{operator}</td><td>{value}</td><td>{from}</td><td>{to}</td></tr>',
            '</tpl>',
            '</table>',
            '<hr>',
            '<h2>Charts</h2>',
            '<table width="100%" border="0">',
            '<tr><td width="25%"><b>Title</b></td><td width="25%"><b>Type</b></td><td width="25%"><b>Field Name</b></td><td width="25%"><b>Data Source</b></td></tr>',
            '<tpl for="charts">',
            '<tr>',
            '<td>{title}</td>',
            '<td>',
            '<tpl if="type == \'pieChart\'">',
            '<i class="fa fa-pie-chart" data-qtip="Pie Chart"></i> Pie',
            '<tpl elseif="type == \'barChart\'">',
            '<i class="fa fa-bar-chart" data-qtip="Bar Chart"></i> Bar',
            '<tpl elseif="type == \'columnChart\'">',
            '<i class="fa fa-column-chart" data-qtip="Column Chart"></i> Column',
            '</tpl>',
            '</td>',
            '<td>{field}</td>',
            '<td>',
            '<tpl if="dataSource == \'FacetQuery\'">',
            'Query',
            '<tpl elseif="dataSource == \'FacetField\'">',
            'Field',
            '</tpl>',
            '</td>',
            '</tr>',
            '</tpl>',
            '</table>',
            '<hr>',
            '<h2>User Criteria</h2>',
            '<table width="50%" border="0">',
            '<tr><td><b>Field Label</b></td><td><b>Field Name</b></td></tr>',
            '<tpl for="criteria">',
            '<tr><td>{fieldLabel}</td><td>{name}</td></tr>',
            '</tpl>',
            '</table>',
            '</tpl>'
        )
    }]
});