Ext.define('SDT.view.dashboardAdmin.panels.SaveConnectedPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.saveConnectedPanel',
    scrollable: true,
    layout: 'anchor',
    items: [{
        xtype: 'dataview',
        itemSelector: 'div.thumb-wrap',
        margin: '10 5 10 5',
        anchor: '100%',
        emptyText: 'No data available',
        store: {
            fields: [
                'title',
                'description',
                'active',
                'dataIndex',
                'charts',
                'criteria',
                'filters'
            ]
        },
        tpl: Ext.create('Ext.XTemplate', 
            '<tpl for=".">',
            '<h2>Summary</h2><br>',
            'Title: {title}<br>',
            'Description: {description}<br>',
            'Active: ',
            '<tpl if="!active">',
            'No',
            '</tpl>',
            '<tpl if="active">',
            'Yes',
            '</tpl>',
            '<br>',
            'Type:</b> {dataIndex}<br>',
            '<hr>',
            '<h2>Applied Filters</h2>',
            '<table width="100%" border="0">',
            '<tr><td width="10%"><b>Field Label</b><td width="10%"><b>Field Name</b></td><td width="10%"><b>Type</b></td><td width="10%"><b>Operator</b></td><td width="20%"><b>Value</b></td><td width="30%"><b>From</b></td><td width="30%"><b>To</b></td></tr>',
            '<tpl for="filters">',
            '<tr><td>{fieldLabel}</td><td>{fieldName}</td><td>{type}</td><td>{operator}</td><td>{value}</td><td>{from}</td><td>{to}</td></tr>',
            '</tpl>',
            '</table>',
            '<hr>',
            '<h2>Charts</h2>',
            '<table width="100%" border="0">',
            '<tr><td width="25%"><b>Title</b></td><td width="25%"><b>Type</b></td><td width="25%"><b>Field Name</b></td><td width="25%"><b>Data Source</b></td></tr>',
            '<tpl for="charts">',
            '<tr>',
                '<td>{title}</td>',
                '<td>',
                '<tpl if="type == \'pieChart\'">',
                '<img class="x-grid-cell-icon icon-chart_pie" data-qtip="Pie Chart" src="' + Ext.BLANK_IMAGE_URL + '"> Pie',
                '<tpl elseif="type == \'barChart\'">',
                '<img class="x-grid-cell-icon icon-chart_bar" data-qtip="Bar Chart" src="' + Ext.BLANK_IMAGE_URL + '"> Bar',
                '<tpl elseif="type == \'columnChart\'">',
                '<img class="x-grid-cell-icon icon-chart_column" data-qtip="Column Chart" src="' + Ext.BLANK_IMAGE_URL + '"> Column',
                '</tpl>',
                '</td>',
                '<td>{field}</td>',
                '<td>',
                '<tpl if="dataSource == \'FacetQuery\'">',
                'Query',
                '<tpl elseif="dataSource == \'FacetField\'">',
                'Field',
                '</tpl>',
                '</td>',
            '</tr>',
            '</tpl>',
            '</table>',
            '<hr>',
            '<h2>User Criteria</h2>',
            '<table width="50%" border="0">',
            '<tr><td><b>Field Label</b></td><td><b>Field Name</b></td></tr>',
            '<tpl for="criteria">',
            '<tr><td>{fieldLabel}</td><td>{name}</td></tr>',
            '</tpl>',
            '</table>',
            '</tpl>'
        )
    }]
});