Ext.define('SDT.view.dashboardAdmin.panels.SaveIndependentPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.saveIndependentPanel',
    scrollable: true,
    layout: 'anchor',
    items: [{
        xtype: 'dataview',
        itemSelector: '',
        margin: '10 5 10 5',
        anchor: '100%',
        store: Ext.create('Ext.data.Store', {
            id: 'saveStore',
            fields: [
                'title',
                'description',
                'active',
                'charts'
            ]
        }),
        tpl: Ext.create('Ext.XTemplate', 
            '<tpl for=".">',
            '<h2>Summary</h2><br>',
            'Title: {title}<br>',
            'Description: {description}<br>',
            'Active: ',
            '<tpl if="!active">',
            'No',
            '</tpl>',
            '<tpl if="active">',
            'Yes',
            '</tpl>',
            '<hr>',
            '<h2>Charts</h2>',
            '<table width="100%" border="0">',
            '<tpl for="charts">',
            '<tr><td width="25%"><b>Title</b></td><td width="25%"><b>Type</b></td><td width="25%"><b>Field Name</b></td><td width="25%"><b>Data Source</b></td></tr>',
            '<tr><td colspan="4"><hr></td></tr>',
            '<tr>',
                '<td>{title}</td>',
                '<td>',
                '<tpl if="type == \'pieChart\'">',
                '<img class="x-grid-cell-icon icon-chart_pie" data-qtip="Pie Chart" src="' + Ext.BLANK_IMAGE_URL + '"> Pie',
                '<tpl elseif="type == \'barChart\'">',
                '<img class="x-grid-cell-icon icon-chart_bar" data-qtip="Bar Chart" src="' + Ext.BLANK_IMAGE_URL + '"> Bar',
                '<tpl elseif="type == \'columnChart\'">',
                '<img class="x-grid-cell-icon icon-chart_column" data-qtip="Column Chart" src="' + Ext.BLANK_IMAGE_URL + '"> Column',
                '</tpl>',
                '</td>',
                '<td>{field}</td>',
                '<td>',
                '<tpl if="dataSource == \'FacetQuery\'">',
                'Query',
                '<tpl elseif="dataSource == \'FacetField\'">',
                'Field',
                '</tpl>',
                '</td>',
            '</tr>',

            '<tr>',
            '<td colspan="4" align="right">',

            '<p style="padding-left:15px;" align="left">',
            '<b>Type:</b>dataIndex<br>',
            '<b>Applied Filters:</b>',
            '</p>',

            '<table width="97%" border="1">',
            '<tr><td width="14%"><b>Field Label</b><td width="14%"><b>Field Name</b></td><td width="14%"><b>Type</b></td><td width="14%"><b>Operator</b></td><td width="14%"><b>Value</b></td><td width="14%"><b>From</b></td><td width="30%"><b>To</b></td></tr>',
            '<tpl for="baseCriteria">',
            '<tr><td>{fieldLabel}</td><td>{fieldName}</td><td>{type}</td><td>{operator}</td><td>{value}</td><td>{from}</td><td>{to}</td></tr>',
            '</tpl>',
            '</table>',

            '</td>',
            '</tr>',

            '<tr>',
            '<td colspan="4" align="right">',

            '<p style="padding-left:15px;" align="left"><b>User Criteria:</b></p>',
            '<table width="97%" border="1">',
            '<tr><td width="50%"><b>Field Label</b></td><td width="50%"><b>Field Name</b></td></tr>',
            '<tpl for="userCriteriaFields">',
            '<tr><td>{fieldLabel}</td><td>{name}</td></tr>',
            '</tpl>',
            '</table>',

            '</td>',
            '</tr>',

            '<tr>',
            '<td colspan="4">&nbsp;</td>',
            '</tr>',

            '</tpl>',
            '</table>',
            '</tpl>'
        )
    }]
});